apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdeploy
  labels:
    app: userdeploy
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: userdeploy
    spec:
      containers:
        - name: userpod
          image: 192.168.132.100/ngtms-test/k8s-orderweb:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      imagePullSecrets:
         - name: regsecret
      restartPolicy: Always
  selector:
    matchLabels:
        app: userdeploy

