eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    response-cache-update-interval-ms: 5000
  client:
    register-with-eureka: false #自己也注册到注册中心
    fetch-registry: false #需要从其他eureka节点获取注册信息
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
server:
  port: 8762
