apiVersion: v1
  kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: default
data:
  filebeat.yml: |
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    filebeat.inputs:
    - type: log
      paths:
        - /app/log/*.log
    output.logstash:
      hosts: ["192.168.132.128:5044"]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: filebeat-logging
spec:
    selector:
      matchLabels:
        name: filebeat-logging
    template:
      metadata:
        labels:
          name: filebeat-logging
      spec:
        containers:
          - name: filebeat-logging
            image: docker.elastic.co/beats/filebeat:6.7.1
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: logpath
                mountPath: /app/log/
                readOnly: true
              - name: filebeatdata
                mountPath: /usr/share/filebeat/data/
              - name: filebeatconfig
                mountPath: /usr/share/filebeat/filebeat.yml
                subPath: filebeat.yml
        terminationGracePeriodSeconds: 30
        volumes:
          - name: logpath
            hostPath:
              path: /app/log/
              type: DirectoryOrCreate
          - name: filebeatdata
            hostPath:
              path: /app/filebeat/data/
              type: DirectoryOrCreate
          - name: filebeatconfig
            configMap:
                name: filebeat-config
                items:
                  - key: filebeat.yml
                    path: filebeat.yml
