apiVersion: apps/v1
kind: Deployment
metadata:
  name: svdeploy
  labels:
    app: svdeploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: svdeploy
    spec:
      containers:
        - name: svpod
          image: 192.168.132.100/ghc/sv:1.0.0
          imagePullPolicy: Always
          volumeMounts:
            - name: logpath
              mountPath: /app/log/
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: /intf
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 1
            successThreshold: 3
            failureThreshold: 3
          livenessProbe:
           httpGet:
             port: 80
             path: /intf
           initialDelaySeconds: 80
           periodSeconds: 15
           timeoutSeconds: 1
           failureThreshold: 3
      imagePullSecrets:
         - name: regsecret
      restartPolicy: Always
      volumes:
        - name: logpath
          hostPath:
            path: /app/log/
            type: DirectoryOrCreate
  selector:
    matchLabels:
        app: svdeploy

