apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdeploy
  labels:
    app: webdeploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: webdeploy
    spec:
      containers:
        - name: webpod
          image: 192.168.132.100/ghc/web:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      imagePullSecrets:
         - name: regsecret
      restartPolicy: Always
  selector:
    matchLabels:
        app: webdeploy

