apiVersion: v1
kind: Service
metadata:
  name: webservice
  labels:
    app: webservice
spec:
  type: NodePort
  selector:
    app: webdeploy
  ports:
    - port: 8082
      nodePort: 30001
      targetPort: 80
